# -*- coding: utf-8 -*-
"""Final_Code_Trustworthy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_4k8mVriiEDpUfR8DxapEtgqSA3E9dx
"""

!pip install tensorflow opencv-python scikit-learn matplotlib gradio

from google.colab import drive
drive.mount('/content/drive')

from sklearn.model_selection import train_test_split

import os
import numpy as np
import cv2
import tensorflow as tf
import matplotlib.pyplot as plt
import gradio as gr
from sklearn.metrics import accuracy_score
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50, DenseNet121, MobileNetV2, InceptionV3, InceptionResNetV2

IMG_SIZE = 128
def load_data(image_dir, mask_dir):
    images, masks = [], []
    image_files = sorted(os.listdir(image_dir))
    mask_files = sorted(os.listdir(mask_dir))

    for img_file, mask_file in zip(image_files, mask_files):
        img_path = os.path.join(image_dir, img_file)
        mask_path = os.path.join(mask_dir, mask_file)
        img = cv2.imread(img_path)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

        if img is None or mask is None:
            continue

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE)) / 255.0
        mask = cv2.resize(mask, (IMG_SIZE, IMG_SIZE))
        mask = np.expand_dims((mask > 0).astype(np.uint8), axis=-1)

        images.append(img)
        masks.append(mask)

    return np.array(images), np.array(masks)

# Load Dataset 1 (for training)
X_train, y_train = load_data('/content/drive/MyDrive/COVID/frames_train/', '/content/drive/MyDrive/COVID/masks_train/')

def build_unet_resnet_hybrid(input_shape=(IMG_SIZE, IMG_SIZE, 3)):
    inputs = tf.keras.Input(shape=input_shape)
    base_model = tf.keras.applications.ResNet50(include_top=False, weights='imagenet', input_tensor=inputs)
    base_model.trainable = False

    skips = [
        base_model.get_layer("conv1_relu").output,
        base_model.get_layer("conv2_block3_out").output,
        base_model.get_layer("conv3_block4_out").output,
        base_model.get_layer("conv4_block6_out").output
    ]
    x = base_model.get_layer("conv5_block3_out").output

    for skip in reversed(skips):
        x = tf.keras.layers.UpSampling2D((2, 2))(x)
        x = tf.keras.layers.Concatenate()([x, skip])
        x = tf.keras.layers.Conv2D(256, 3, activation='relu', padding='same')(x)
        x = tf.keras.layers.Conv2D(256, 3, activation='relu', padding='same')(x)

    x = tf.keras.layers.UpSampling2D((2, 2))(x)
    x = tf.keras.layers.Conv2D(128, 3, activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(64, 3, activation='relu', padding='same')(x)

    outputs = tf.keras.layers.Conv2D(1, 1, activation='sigmoid')(x)
    return tf.keras.Model(inputs, outputs)

model = build_unet_resnet_hybrid()
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=6, batch_size=8, validation_split=0.1, steps_per_epoch=100)
model.save('/content/drive/MyDrive/COVID_Models/unet_resnet_model.h5')

def evaluate_model(model, X, y):
    preds = model.predict(X)
    preds = (preds > 0.5).astype(np.uint8)
    acc = accuracy_score(y.flatten(), preds.flatten())
    return acc

unet_resnet_model = tf.keras.models.load_model('/content/drive/MyDrive/COVID_Models/unet_resnet_model.h5')
test_acc = evaluate_model(unet_resnet_model, X_test, y_test)
print(f"✅ Test Accuracy on Dataset 2: {test_acc*100:.2f}%")

def dice_coef(y_true, y_pred, smooth=1e-6):
    y_true_f = y_true.flatten()
    y_pred_f = y_pred.flatten()
    intersection = np.sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (np.sum(y_true_f) + np.sum(y_pred_f) + smooth)

preds = (unet_resnet_model.predict(X_test) > 0.5).astype(np.uint8)
dice = dice_coef(y_test, preds)
print(f"🧪 Dice Coefficient on Dataset 2: {dice:.4f}")

import gradio as gr
import cv2

# Load trained model
model = tf.keras.models.load_model('/content/drive/MyDrive/COVID_Models/unet_resnet_model.h5')

# Prediction function
def predict_ct(image):
    # Resize to match model input
    image_resized = cv2.resize(image, (IMG_SIZE, IMG_SIZE)) / 255.0
    image_input = np.expand_dims(image_resized, axis=0)  # Add batch dimension

def predict_ct(image):
    image_resized = cv2.resize(image, (IMG_SIZE, IMG_SIZE)) / 255.0
    image_input = np.expand_dims(image_resized, axis=0)

    # Predict the mask
    pred_mask = model.predict(image_input)[0]
    pred_mask = (pred_mask > 0.5).astype(np.uint8) * 255

    # Create overlay
    overlay = image_resized.copy()
    overlay_mask = pred_mask.squeeze().astype(np.uint8)
    overlay_mask_colored = cv2.merge([overlay_mask]*3)
    overlay = (0.6 * overlay * 255 + 0.4 * overlay_mask_colored).astype(np.uint8)

    return overlay

def predict_ct(image):
    # Resize and normalize
    image_resized = cv2.resize(image, (IMG_SIZE, IMG_SIZE)) / 255.0
    image_input = np.expand_dims(image_resized, axis=0)

    # Predict the mask
    pred_mask = model.predict(image_input)[0]
    pred_mask_bin = (pred_mask > 0.5).astype(np.uint8) * 255
    pred_mask_bin = pred_mask_bin.squeeze()

    # Convert grayscale mask to 3 channels
    pred_mask_colored = cv2.merge([pred_mask_bin] * 3)

    # Convert original to display range
    image_disp = (image_resized * 255).astype(np.uint8)

    # Overlay mask on original image
    overlay = cv2.addWeighted(image_disp, 0.7, pred_mask_colored, 0.3, 0)

    # Stack all three: original | mask | overlay
    combined = np.hstack([image_disp, pred_mask_colored, overlay])
    return combined

gr.Interface(
    fn=predict_ct,
    inputs=gr.Image(type="numpy", label="Upload CT Image"),
    outputs=gr.Image(type="numpy", label="Original | Mask | Overlay"),
    title="COVID-19 CT Scan Segmentation",
    description="Left: Original CT, Middle: Infection Mask, Right: Overlay"
).launch()